### ISSUE TITLE
What should I eat for dinner tonight?

### ISSUE THREAD

**Issue by lindseymetz87** [Openscapes/2022-swrcb#14]
I only eat vegetarian or seafood, I am in the mood for Italian, Indian or Tai. HELP!

**Comment by AHolder1** [comment]
Tacos!

**Comment by aekdunn** [comment]
Green Elephant in Loomis - Burmese food! @lindseymetz87

**Comment by j-a-bennett** [comment]
[Dos Coyotes](https://doscoyotes.com/)
