### ISSUE TITLE
Week prior email

### ISSUE THREAD

**Issue by cclatterbuck** [Openscapes/2022-swrcb#8]
Approve prior to send on 8/10:

- [x] Anna
- [x] Corey

Clarify before sending email:

- [x] Are individuals invited to the GitHub cohort/team and/or [2022-SWRCB] google drive prior to this email? Kyber suggests the cohort is not added to the GitHub repo prior to the Clinic, but this template states otherwise

**Welcome to Openscapes – SWRCB Champions Cohort**

Hello All,

We are so excited to welcome you to the 2022 SWRCB Openscapes Champions Cohort! Our first Cohort Call is in one week on August 17th and we wanted to share some information with you.

[Openscapes](https://openscapes.org/) is an approach for doing better science in less time. Through the Champions program we help research groups reimagine data-intensive science, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive research communities. Our Cohort is supported by the deputy directors and assistant deputy directors of DWR -- Karen Mogus, Phillip Crader, and Annalisa Kihara -- and OIMA deputy director Greg Gearheart. Thanks for creating the time for us to think about our work!

_Cohort Logistics_

Details and short intros of participating teams are at https://openscapes.github.io/2022-swrcb. If you have edits, we will do so through GitHub – and if you don’t yet know how to do this, you’ll learn in our GitHub Clinic in Call 3!

Before August 17th, please:

- Check that you’ve received calendar invites with Teams links for our 5 Cohort Calls starting Aug 17. If you have not received these invites, please let us know.
- Read [Lowndes et al 2017](https://www.nature.com/articles/s41559-017-0160): Our path to better science in less time using open data science tools. Optionally, you can also review the slides/video of a [recent plenary](https://www.openscapes.org/blog/2021/08/01/sortee-plenary/).
- Schedule “Seaside Chats”: In the alternating weeks when we do not meet as a cohort, your task will be to meet as a team to further discuss and apply what we learn to your work. We call these meetings “[Seaside Chats](https://github.com/Openscapes/seaside-chats)” and suggest you schedule them with your team now (does not have to include unit/organizational lead).

All cohort events abide by the Openscapes [Code of Conduct](https://openscapes.org/code-of-conduct), which aligns with the [Water Boards Racial Equity Resolution](https://www.waterboards.ca.gov/racial_equity/resolution-and-actions.html). 

We will be recording all Cohort Calls. They will be available for you if you miss a meeting or to use as a reference, and to help us improve the program, but not shared publicly. If you have any concerns about being recorded, please let us know.

The Champions Program is designed for you to all participate actively with your team and across teams in the cohort, so please come prepared to engage with your colleagues. Within your team and across teams we have a mix of backgrounds, technical/coding/data experience, responsibilities, and more – this is intentional. You are all welcome here and provide value to our cohort; there are no technical prerequisites to participate.

_Meet the Openscapes team_

We’re the team you’ll see most often on the calls, along with a few guest speakers:

- [Corey Clatterbuck](http://www.coreyclatterbuck.com), Environmental Scientist in OIMA
- Anna Holder, Environmental Scientist & Tribal Coordinator in OIMA
- Devan Burke, Associate Governmental Program Analyst & Training Coordinator in OIMA
- Tina Ures, Engineering Geologist in DWR

Please let us know if you have any questions. Thank you for being a part of it; we have an exciting group assembled and we’re looking forward to getting to know all of you and strengthening relationships within the Cohort.

Cheers,

Corey, Anna, Devan, & Tina

**Comment by AHolder1** [comment]
@cclatterbuck sent email 8/10/2022
